version: "3.9"

services:
  pyrogram-bot:
    build: .
    container_name: album_bot_auto
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Kolkata  # Adjust to your timezone
